### ISSUE TITLE
Preliminary tests on the AMO setup

### ISSUE THREAD

**Issue by valegagge** [icub-tech-iit/study-encoders#31]
## Task description :memo:
We want to perform some preliminary tests to point out one or possible causes of the AMO fault.

Here the list of the tests:
 - [x] run the joint in `velocity` control mode with a low speed. (No Ferrites used)
 - [x] run the joint in `velocity` control mode with a high speed. (No Ferrites used)
 - [x] run the joint and disconnect the SPI cable (to simulate a cable broken)
 - [x] run the joint in `position `control mode and bring the AMO head near to the magnetic strip. 
 - [x] run the joint in `position `control mode and bring the AMO head far from the magnetic strip. 

## Definition of Done :white_check_mark:
All tests done and reported here the results.

Publish also the script used to analyze the data
