### ISSUE TITLE
Validate Aksim - STINT 1

### ISSUE THREAD

**Issue by valegagge** [icub-tech-iit/study-encoders#32]
## Task description :memo:
Using the` third-encoder-setup` we want to test and validate the Aksim encoder.

- [x] Get acquainted with the setup and Aksim
- [x] Test cases:
    - [x] Low velocity (20 deg/sec)
    - [x] High velocity (60 deg/sec)
    - [x] Disconnect the cable
    - [x] With/without Ferrites
    - [x] Simulate voltage dispersion

## Definition of Done :white_check_mark:
Test done and the results reported here
