### ISSUE TITLE
Validate the encoder diagnostic of 2foc fw.

### ISSUE THREAD

**Issue by valegagge** [icub-tech-iit/study-encoders#6]
## Task description :memo:
Following the work done in #2, we want to validate the 2foc diagnostic.

It's important to notice that the emulated encoder has been validated by oscilloscope only.

Steps:
 - [x] request the cable for the emulated encoder
 - [x] Create the setup + oscilloscope
 - [x] performs tests:
       - [ ] normal running
       - [ ] run at different speeds
       - [ ] trigger index error.

## Definition of Done :white_check_mark:
Tests done and results reported here
